Insert into nationalities (nationality) values ('Singapore'); 
Insert into nationalities (nationality) values ('Italia'); 
Insert into nationalities (nationality) values ('Norway'); 
Insert into nationalities (nationality) values ('Iceland'); 
Insert into nationalities (nationality) values ('Other'); 
Insert into nationalities (nationality) values ('Israel'); 
Insert into nationalities (nationality) values ('UK'); 
Insert into nationalities (nationality) values ('Russia'); 
Insert into nationalities (nationality) values ('Canada'); 
Insert into nationalities (nationality) values ('Denmark'); 
Insert into nationalities (nationality) values ('Taiwan'); 
Insert into nationalities (nationality) values ('Poland'); 
Insert into nationalities (nationality) values ('Spain'); 
Insert into nationalities (nationality) values ('Belgium'); 
Insert into nationalities (nationality) values ('France'); 
Insert into nationalities (nationality) values ('China'); 
Insert into nationalities (nationality) values ('India'); 
Insert into nationalities (nationality) values ('SouthKorea'); 
Insert into nationalities (nationality) values ('Estonia'); 
Insert into nationalities (nationality) values ('USA'); 
Insert into nationalities (nationality) values ('Japan'); 
Insert into nationalities (nationality) values ('Ireland'); 
Insert into nationalities (nationality) values ('Switzerland'); 
Insert into nationalities (nationality) values ('Germany'); 
Insert into nationalities (nationality) values ('Sweden'); 
Insert into nationalities (nationality) values ('Australia'); 
Insert into nationalities (nationality) values ('Finland'); 
Insert into nationalities (nationality) values ('Austria'); 
Insert into nationalities (nationality) values ('HongKong'); 
Insert into nationalities (nationality) values ('Netherlands'); 
Insert into passengers (nationality, year, month, passengercount) values ('Iceland', 2002, '03', 16966); 
Insert into passengers (nationality, year, month, passengercount) values ('Iceland', 2002, '04', 16655); 
Insert into passengers (nationality, year, month, passengercount) values ('Iceland', 2002, '05', 19969); 
Insert into passengers (nationality, year, month, passengercount) values ('Iceland', 2002, '06', 28034); 
Insert into passengers (nationality, year, month, passengercount) values ('Iceland', 2002, '07', 26846); 
Insert into passengers (nationality, year, month, passengercount) values ('Iceland', 2002, '08', 25957); 
